### ISSUE TITLE
Neustart falls Gridbox Dienst offline 

### ISSUE THREAD

**Issue by don-o-mat** [unl0ck/homeassistant-addon-viessmann-gridbox#54]
Hallo @unl0ck 
Das add-on bleibt bei mir öfter mal ohne ersichtlichen Grund stehen, ca 3 mal pro Woche, und der watchdog schafft es dann anscheinend nicht, es neu zu starten. 

Könntest du da was nachbessern? Ich habe den Eindruck, das könnte evtl mit der zeitweise holprigen Erreichbarkeit des Gridbox Dienstes zu tun haben. 

Besten Dank!

**Comment by unl0ck** [comment]
ja ich muss da unbedingt ran, problem ist nur, dass ich die logs nie sehe bei mir, wieso auch immer. werd da mal ein Fehlermeldesystem einbauen. 
danke für die info, sorry für die umständlichkeiten.

**Comment by unl0ck** [comment]
Ich hatte schon weitergearbeitet aber es taucht gerade das 2. Gerät nicht auf, dass muss ich nochmal untersuchen. Wieso.
Aber ansonsten sollte das Edge starten

**Comment by Lendelfinger** [comment]
Hallo @don-o-mat,

ich habe seit einiger Zeit eine kleine Automatisierung laufen, die checkt, ob das Add-on eingefroren ist.
Falls ja, wird es automatisch neu gestartet. Bisher läuft das Teil recht gut.

Hier mal der entsprechende YAML-Code:

```
alias: Gridbox Restart
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.viessmann_gridbox_consumption
    for:
      hours: 0
      minutes: 1
      seconds: 0
conditions: []
actions:
  - action: hassio.addon_restart
    data:
      addon: "NAME DES ADD-ONS" (ohne " ")
mode: single

```
